# Generated by Django 3.2.8 on 2021-10-19 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(choices=[('RANDOM_3D_ITEM', 'RANDOM_3D_ITEM'), ('DONATE', 'DONATE'), ('WAIVE_LATE_ATTENDANCE', 'WAIVE_LATE_ATTENDANCE'), ('RESUBMIT', 'RESUBMIT'), ('+1_MARK', '+1_MARK'), ('WAIVE_LATE_SUBMISSION', 'WAIVE_LATE_SUBMISSION')], max_length=80)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_donated', models.BooleanField(default=False)),
                ('donated_from', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('instructr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
