# Generated by Django 3.2.8 on 2021-10-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='prize',
            field=models.CharField(blank=True, choices=[('+1_MARK', '+1_MARK'), ('DONATE', 'DONATE'), ('RANDOM_3D_ITEM', 'RANDOM_3D_ITEM'), ('RESUBMIT', 'RESUBMIT'), ('WAIVE_LATE_SUBMISSION', 'WAIVE_LATE_SUBMISSION'), ('WAIVE_LATE_ATTENDANCE', 'WAIVE_LATE_ATTENDANCE')], max_length=80),
        ),
    ]
