# Generated by Django 3.2.8 on 2021-10-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20211020_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='donated_to',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='point',
            name='prize',
            field=models.CharField(blank=True, choices=[('DONATE', 'DONATE'), ('WAIVE_LATE_ATTENDANCE', 'WAIVE_LATE_ATTENDANCE'), ('WAIVE_LATE_SUBMISSION', 'WAIVE_LATE_SUBMISSION'), ('RANDOM_3D_ITEM', 'RANDOM_3D_ITEM'), ('+1_MARK', '+1_MARK'), ('RESUBMIT', 'RESUBMIT')], max_length=80),
        ),
    ]
