# Generated by Django 3.2.8 on 2021-10-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_auto_20211020_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='prize',
            field=models.CharField(blank=True, choices=[('WAIVE_LATE_ATTENDANCE', 'WAIVE_LATE_ATTENDANCE'), ('RANDOM_3D_ITEM', 'RANDOM_3D_ITEM'), ('WAIVE_LATE_SUBMISSION', 'WAIVE_LATE_SUBMISSION'), ('RESUBMIT', 'RESUBMIT'), ('+1_MARK', '+1_MARK'), ('DONATE', 'DONATE')], max_length=80),
        ),
    ]
