# Generated by Django 3.2.8 on 2021-10-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_alter_point_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='prize',
            field=models.CharField(blank=True, choices=[('WAIVE_LATE_ATTENDANCE', 'WAIVE_LATE_ATTENDANCE'), ('+1_MARK', '+1_MARK'), ('DONATE', 'DONATE'), ('RESUBMIT', 'RESUBMIT'), ('RANDOM_3D_ITEM', 'RANDOM_3D_ITEM'), ('WAIVE_LATE_SUBMISSION', 'WAIVE_LATE_SUBMISSION')], max_length=80),
        ),
    ]
