version: '3'

services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn RMS.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on: 
      - db

  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=staging_rms
    volumes:
      - ./postgres_data:/var/lib/postgresql
      - ./dbbackups:/backups

    ports:
        - 25432:5432
    restart: on-failure
    healthcheck:
        test: "exit 0"