# Generated by Django 3.2.8 on 2021-10-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='reward',
            field=models.CharField(choices=[('Waive Late of class penalty', 'Waive Late of class penalty'), ('Waive Late Assignment Penalty', 'Waive Late Assignment Penalty'), ('+1 mark on any submission', '+1 mark on any submission'), ('Resubmit attempt', 'Resubmit attempt')], max_length=80),
        ),
    ]
