# Generated by Django 3.2.8 on 2021-11-02 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('instructor', models.CharField(max_length=100)),
                ('tas', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='courses.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Rewads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.CharField(choices=[('Resubmit attempt', 'Resubmit attempt'), ('+1 mark on any submission', '+1 mark on any submission'), ('Waive Late Assignment Penalty', 'Waive Late Assignment Penalty'), ('Waive Late of class penalty', 'Waive Late of class penalty')], max_length=80)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.students')),
            ],
        ),
    ]
