# Generated by Django 3.2.8 on 2021-10-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ta',
            field=models.BooleanField(default=False),
        ),
    ]
